#!/bin/env bash

# DESCRIPTION: PlanV CI System Runner
#
# Property of PlanV GmbH, 2024. All rights reserved.
# Contact: yilou.wang@planv.tech

SCRIPT_DIR=$(realpath "$(dirname "$0")")

source "$SCRIPT_DIR/set_build_run_functions"

branch="master"
test_dir="$SCRIPT_DIR/planv_tests/feature_tests"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --setup)
            echo "### Running setup for test directory : $test_dir ###"
            setup "$test_dir"
            shift
            ;;
        --build)
            shift
            echo "### Building Verilator on branch: $1 ###"
            build "$1"
            shift
            ;;
        --run_tests)
            shift
            echo "### Running tests on branch: $1 ###"
            run_tests "$1"
            shift
            ;;
        *) 
            echo "Option $1 not recognized" >&2
            exit 1
            ;;
    esac
done

# If no options provided, run all
echo "### Running setup for test directory : $test_dir ###"
setup "$test_dir"

echo "### Building Verilator on branch: $branch ###"
build "$branch"

echo "### Running tests on branch: $branch ###"
run_tests "$branch"

echo "### All tasks completed. ###"
