#!/bin/env bash

# DESCRIPTION: PlanV User Run Script
#
# Property of PlanV GmbH, 2024. All rights reserved.
# Contact: yilou.wang@planv.tech

echo "Arguments received: $@"
SCRIPT_DIR=$(realpath $(dirname "$0"))

source "$SCRIPT_DIR/set_build_run_functions"

branch="master"
test_dir="$SCRIPT_DIR/planv_tests/feature_tests"

while [[ $# -gt 0 ]]; do
    echo "Current option: $1"
    case "$1" in
        -b|--branch) 
            echo "Branch option recognized: $2"
            branch="$2"
            shift 2 
            ;;
        -t|--test-dir) 
            echo "Test directory option recognized: $2"
            test_dir="$2"
            shift 2 
            ;;
        -h|--help)
            echo "Usage: $0 [-b <branch>] [-t <test_dir>]" >&2
            exit 1 
            ;;
        *)
            echo "Unknown option: $1" >&2
            exit 1 
            ;;
    esac
done

test_dir=$(realpath "$test_dir")

create_logdir

echo "### Running setup for test directory : $test_dir ###"
setup "$test_dir"

echo "### Building Verilator on branch: $branch ###"
build "$branch"

echo "### Running tests on branch: $branch ###"
run_tests "$branch"

echo "### All tasks completed. ###"
