name: PlanV Verilator Feature Tests

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 7 * * *"

jobs:
  generate-matrix:
    name: Generate Branch Matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.create_matrix.outputs.matrix }}
    steps:
      - name: Checkout verilator repo from PlanV github
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
          clean: false
      
      - name: Check how many branches there are, and process one by one.
        id: create_matrix
        run: echo "::set-output name=matrix::$(ls verilator | jq -R -s -c 'split("\n")[:-1]')"
  
  test:
    name: Test Branch ${{ matrix.VERILATOR_BRANCH }}
    needs: generate-matrix
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        VERILATOR_BRANCH: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}

    env:
      CCACHE_COMPRESS: 1
      CCACHE_DIR: ${{ github.workspace }}/.ccache
      CCACHE_LIMIT_MULTIPLE: 0.95
      CCACHE_MAXSIZE: 150M

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          clean: false

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Enable Dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install git help2man perl python3 make autoconf flex bison ccache # Prerequisites from verilator manual
          sudo apt-get -y install gcc-12 g++-12 # in planv, we "scl enable gcc-toolset-12 bash" to hold a 12 version g++.
          sudo apt-get install -y libunwind-dev
          sudo apt-get -y install libgoogle-perftools-dev numactl perl-doc
          sudo apt-get -y install libfl2 || true  # Ubuntu only (ignore if gives error)
          sudo apt-get -y install libfl-dev || true  # Ubuntu only (ignore if gives error)
          sudo apt-get -y install zlibc zlib1g zlib1g-dev || true  # Ubuntu only (ignore if gives error)
          sudo pip3 install pyyaml jinja2 robotframework z3-solver # configparser
          sudo pip3 install jinja2 # for html polishing

      - name: Cache Compilation Outputs
        uses: actions/cache@v2
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ${{ matrix.VERILATOR_BRANCH }}

      - name: Make setup_and_build script executable
        run: |
          chmod +x scripts/setup_and_build
          chmod +x scripts/setup_feature_tests_sim_framework

      - name: Create logs folder and setup_and_build log file
        run: |
          mkdir -p logs
          touch logs/setup_and_build.log

      - name: Setup Repo
        run: scripts/setup_and_build --setup
      
      - name: Build Verilator
        env:
          CC: gcc-12
          CXX: g++-12
        run: scripts/setup_and_build --build ${{ matrix.VERILATOR_BRANCH }}

      - name: Run Tests
        run: scripts/setup_and_build --run-tests ${{ matrix.VERILATOR_BRANCH }}

      - name: Verify logs existence
        run: ls -l logs

      - name: Upload logs
        uses: actions/upload-artifact@v3
        with:
          path: logs/
          name: test-output-${{ matrix.VERILATOR_BRANCH }}

      - name: Upload test report
        uses: actions/upload-artifact@v2
        with:
          name: test-report-${{ github.ref_name }}
          path: test_report_${{ github.ref_name }}.html